apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
  - name: output
  steps:
  - name: clone
    image: alpine/git
    script: |
      #!/bin/sh
      git clone https://github.com/tcessil/ci-cd-final-project.git $(workspaces.output.path)