apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: example-pipelinerun
spec:
  pipelineRef:
    name: example-pipeline
  workspaces:
  - name: output
    persistentVolumeClaim:
      claimName: oc-lab-pvc